### ISSUE TITLE
Databases with dashes in the name cannot be created

### ISSUE THREAD

**Issue by ThomasHoppe** [HTWHub/ocean#27]
The description on the Ocean Plattform:

"They can be between 4 and 32 characters long and may contain dashes." is not correct. If I choose a DB-Name with a dash in it, the DB will not be created.

If the starts with less than 2 letters followed by a dash, like "db-hoppe-test", the error message "Name should be of minimum 4 characters length" is displayed.

This indicates that the dashes are not processed properly.

Either remove the statement that dashes can be part of a name, or correct this bug.

**Comment by abteilung6** [comment]
According to [https://www.postgresql.org/docs/7.0/syntax525.htm](https://www.postgresql.org/docs/7.0/syntax525.htm) underscores are allowed and not dashes.

So we replace dashes by underscores. 

`/^[a-z][a-z0-9_]*$/`
